### ISSUE TITLE
CI Script Modifications

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-browser-base#4]
Some minor tweaks to the CI behavior:
- Push images to `:latest` when a commit is made to `main`
- Create a draft release for current Chrome and Brave versions (if aren't already existing) on push to `main`
- Push images to corresponding release tag when the release is made in GH
Bonus:
- Set description of release draft to point to the images that will be published eg.
```
This release publishes the image: `webrecorder/browsertrix-browser-base:$VERSION`

The image is hosted [on DockerHub](https://hub.docker.com/r/webrecorder/browsertrix-browser-base/tags?name=$VERSION)
```

**Comment by tw4l** [comment]
Commit https://github.com/webrecorder/browsertrix-browser-base/commit/9f6ccc2c997990cbeb2129101145e34a79169c5e makes all of the above changes except the first (to push images to `:latest` when a commit is made to `main`).

Since we know have `:brave-VERSION` and `:chrome-VERSION` tags, it seems reasonable to also have `:brave-latest` and `:chrome-latest` tags as well. But which images should have the universal `:latest` tag - latest Chrome?

**Comment by tw4l** [comment]
Completed in https://github.com/webrecorder/browsertrix-browser-base/commit/baa05690536d0eec66efca79398b3c9a3ad40175, `:latest` tag is used for Chrome for now

**Comment by tw4l** [comment]
I had the tags backwards between `-publish` and `-release` workflows. Fixed in https://github.com/webrecorder/browsertrix-browser-base/commit/bdf9a46e39650ef19291718b1bfdfc53f8af5bf4 so that `:chrome-latest`, `:brave-latest`, and `:latest` are only published on publishing a release, and specific browser version tags are released on push to `main`.

**Comment by tw4l** [comment]
Draft release screenshot:

![image](https://user-images.githubusercontent.com/6758804/211398756-410d7a85-5482-4698-8e53-5d323fd99c71.png)
